### ISSUE TITLE
Build failed for iOS: Undefined symbols for architecture arm64: "_OBJC_CLASS_$_SentryId"

### ISSUE THREAD

**Issue by k-ogawa-1988** [getsentry/sentry-kotlin-multiplatform#211]
### Platform

Apple, Android

### Installed

Swift Package Manager

### Version

0.5.0

### Steps to Reproduce

1. Add `io.sentry:sentry-kotlin-multiplatform:0.5.0` to `sourceSets.commonMain.dependencies` in `build.gradle.kts`

```kotlin
kotlin {
    // snip

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation("io.sentry:sentry-kotlin-multiplatform:0.5.0")
        }
    }
}
```

2. Add sentry-cocoa using `sentry-wizard -i ios`

3. Move initialize code using [Shared initializer](https://docs.sentry.io/platforms/kotlin-multiplatform/initialization-strategies/#shared-initializer)

```kotlin
// commonMain/SentryInit.kt

fun initializeSentry() {
    Sentry.init { /* setting */ }
}
```

```kotlin
// androidMain/MainApplication.kt
class MainApplication : Application() {
    override fun onCreate() {
        super.onCreate()
        initializeSentry()
    }
}
```

```swift
// iosMain/iOSApp.swift
import ComposeApp

@main
struct iOSApp: App {
    init() {
        SentryInitKt.intializeSentry()
    }
}
```

4. Build both Android (on Android Studio) and iOS (on XCode)

### Expected Result

Build success.

### Actual Result

- Android: Build success and Sentry got works well.
- iOS: Link app failed with the message below.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SentryId", referenced from:
       in ComposeApp[arm64][2727](libio.sentry:sentry-kotlin-multiplatform-cache.a.o)
ld: symbol(s) not found for architecture arm64
```

**Comment by buenaflor** [comment]
Hi which version of cocoa sdk are you using?

**Comment by buenaflor** [comment]
Not sure which version is added through the wizard

**Comment by buenaflor** [comment]
Assuming you are using only SPM then you'll need to add extra c flags within xcode: 
<img width="1056" alt="image" src="https://github.com/getsentry/sentry-kotlin-multiplatform/assets/23364143/d78188b1-beb3-4894-9ff5-c2036779dbbc">

Otherwise we recommend installing the KMP SDK as per our guide: https://docs.sentry.io/platforms/kotlin-multiplatform/

**Comment by buenaflor** [comment]
This problem should be fixed with the next release `0.6.0`

**Comment by k-ogawa-1988** [comment]
> which version of cocoa sdk are you using?
Using 8.25.0.

I'll try using cocoapods.

**Comment by buenaflor** [comment]
fyi currently our KMP SDK only works with versions up to 8.21.0, please look at this [table](https://docs.sentry.io/platforms/kotlin-multiplatform/#cocoa-sdk-version-compatibility-table) to check what works

**Comment by buenaflor** [comment]
Our next release will support versions starting from 8.22

**Comment by k-ogawa-1988** [comment]
@buenaflor It works now, thank you!
