### ISSUE TITLE
Crashes on App Boot

### ISSUE THREAD

**Issue by alexwhb** [getsentry/sentry-kotlin-multiplatform#190]
### Platform

Android

### Installed

None

### Version

0.5.0, 0.4.0

### Steps to Reproduce

Here's the stack trace I'm getting. Note that sentry has worked on version 0.3.0. I also tried on 0.4.0 with this same error, so it must be something that changed between 0.3.0 and 0.4.0... and maybe it's something I'm missing with my config. 

Here's my config: 
```kotlin
fun setupSentry(isAndroid: Boolean, isDebug: Boolean, releaseVersion: String) {
    Sentry.init {
        it.attachScreenshot = false
        it.dsn =
            if (isAndroid) "real-dsn-here"
            else  "real-dsn-here"
        it.debug = isDebug
        it.environment = if (isDebug) "debug" else "production"
        it.release = releaseVersion
        it.maxBreadcrumbs = 70
    }
}
```

 FATAL EXCEPTION: main
                                                                                                    Process: package.name, PID: 4932
                                                                                                    java.lang.NoSuchMethodError: No virtual method addIntegrationToSdkVersion()V in class Lio/sentry/android/fragment/FragmentLifecycleIntegration; or its super classes (declaration of 'io.sentry.android.fragment.FragmentLifecycleIntegration' appears in /data/app/~~1VNO9HBnEo_R9bdisoohmA==/packagename-bUz5GEsn5UxIMnpxjvKOQg==/base.apk!classes29.dex)
                                                                                                    	at io.sentry.android.fragment.FragmentLifecycleIntegration.register(FragmentLifecycleIntegration.kt:51)
                                                                                                    	at io.sentry.Sentry.init(Sentry.java:253)
                                                                                                    	at io.sentry.Sentry.init(Sentry.java:165)
                                                                                                    	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:87)
                                                                                                    	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:70)
                                                                                                    	at io.sentry.kotlin.multiplatform.SentryInit_androidKt.initSentry(SentryInit.android.kt:14)
                                                                                                    	at io.sentry.kotlin.multiplatform.SentryBridge.init(SentryBridge.jvm.kt:21)
                                                                                                    	at io.sentry.kotlin.multiplatform.Sentry.init(SentryKMP.kt:43)
                                                                                                    	at com.example.MiscUtilsKt.setupSentry(MiscUtils.kt:40)
                                                                                                    	at com.example.ui.BSAApplication.onCreate(BSAApplication.kt:44)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

### Expected Result

Not to crash

### Actual Result

it crashes. 😂

## Update: 
v0.5.0 works 100% fine on iOS, so that's a super excellent highlight.

**Comment by buenaflor** [comment]
hey! sry to hear that, do you use our android gradle plugin as well? if yes how does the setup look like

**Comment by buenaflor** [comment]
it most likely happens because you're importing a conflicting dependency. so if you're using our gradle plugin you're also pulling in an older version of android which is not compatible starting with `0.4.0` 

in that case you can do the following in your `build.gradle.kts`

```kotlin
sentry {
    autoInstallation.enabled.set(false)
}
```

this should be documented better in our kmp docs

**Comment by alexwhb** [comment]
@buenaflor thanks as always for your quick response. I'll give this a try. 👍👍

**Comment by alexwhb** [comment]
@buenaflor solved! my sentry gradle plugin was out of date. I was on 3.11.1, after updating to 4.3.1 all is well. Thanks so much for your help. I'm closing this issue.
